Repository AyishikD/shopify, pull requests merged in 2025-03, with the labels that each got.

#9 [ENHANCEMENT]: Image Click Redirection
  app/[category]/page.tsx
  app/components/Newest.tsx
Labels: enhancement, easy, apertre2.0

#10 Added Footer Section
  app/[category]/page.tsx
  app/components/Footer.tsx
  app/layout.tsx
  app/page.tsx
  app/product/[slug]/page.tsx
  package-lock.json
  package.json
Labels: enhancement, good first issue, medium, apertre2.0

#12 [FEAT] : Product Image change on hover
  app/components/ImageGallery.tsx
Labels: easy, apertre2.0

#14 fix: dollar sign in checkout
  app/components/ShoppingCartModal.tsx
Labels: easy, apertre2.0

#22 ENHANCMENT : Improve tab style in home page
  app/components/CustomCarousel.tsx
  app/components/Hero.tsx
  app/components/Newest.tsx
  components/ui/carousel.tsx
  package-lock.json
  package.json
Labels: enhancement, medium, apertre2.0

#24 Create Code of Conduct.md
  Code of Conduct.md
Labels: good first issue, easy, apertre2.0

#29 Fix Navbar
  .gitignore
  app/layout.tsx
Labels: easy, apertre2.0

#32 [FEAT] : Zoom Feature like Flipkart and amazon
  app/components/CustomCarousel.tsx
  app/components/ImageGallery.tsx
Labels: easy, apertre2.0

#37 improved navbar
  app/components/Navbar.tsx
Labels: easy, apertre2.0

#45 add increment and decrement functionality to shopping cart modal
  app/components/ShoppingCartModal.tsx
Labels: easy, apertre2.0

#42 Make the payment route auth protected
  app/api/webhooks/clerk/route.ts
  app/components/CheckoutNow.tsx
  app/stripe/success/page.tsx
  middleware.ts
Labels: medium, apertre2.0

#48 Navbar and Footer responsiveness fixed
  app/components/CustomCarousel.tsx
  app/components/Navbar.tsx
  app/page.tsx
  components/ui/button.tsx
  components/ui/carousel.tsx
  package-lock.json
Labels: easy, apertre2.0
